[
   {
      "id":"1",
      "name":"Ullu",
      "image":"https://i.ibb.co/7ykmSc2/Ullu.jpg",
      "genre":"Ullu"
   },
   {
      "id":"2",
      "name":"Kooku",
      "image":"https://i.ibb.co/ccT5Vb0/kooku-logo.jpg",
      "genre":"Kooku"
   },
   {
      "id":"3",
      "name":"Hot MX",
      "image":"https://i.ibb.co/W5pt2mS/Hot-Mx-mod-apk-download.jpg",
      "genre":"HotMX"
   },
   {
      "id":"4",
      "name":"Rabbit Movies",
      "image":"https://i.ibb.co/2h47sHf/rabbbit-movies.png",
      "genre":"RabbitMovies"
   },
   {
      "id":"5",
      "name":"Filmy Murga",
      "image":"https://i.ibb.co/kx3CGJQ/filmymurga.jpg",
      "genre":"FilmyMurga"
   },
   {
      "id":"6",
      "name":"Poonam Pandey",
      "image":"https://i.ibb.co/YDJHccC/poonam-Pandey.jpg",
      "genre":"Poonam Pandey"
   },
   {
      "id":"7",
      "name":"Sherlyn Chopra",
      "image":"https://i.ibb.co/P9RqqWq/sherlyn.jpg",
      "genre":"Sherlyn Chopra"
   },
   {
      "id":"9",
      "name":"DigimoviePlex",
      "image":"https://i.ibb.co/bdvCybL/digimovieplex.jpg",
      "genre":"DigimoviePlex"
   },
   {
      "id":"10",
      "name":"Prime Flix",
      "image":"https://i.ibb.co/whpBH2x/prime-Flix.jpg",
      "genre":"PrimeFlix"
   },
   {
      "id":"11",
      "name":"BoomMovies",
      "image":"https://i.ibb.co/KbJqC04/boommovies.jpg",
      "genre":"BoomMovies"
   },
   {
      "id":"12",
      "name":"PrimeShots",
      "image":"https://i.ibb.co/RTpDX96/Prime-Shots.jpg",
      "genre":"PrimeShots"
   },
   {
      "id":"13",
      "name":"HotMasti",
      "image":"https://i.ibb.co/z2VrHXT/HotMasti.jpg",
      "genre":"HotMasti"
   },
   {
      "id":"14",
      "name":"CinePrime",
      "image":"https://i.ibb.co/dkPgN5n/cineprime.png",
      "genre":"CinePrime"
   },
   {
      "id":"15",
      "name":"HalKut",
      "image":"https://i.ibb.co/S79LBz1/halkut.jpg",
      "genre":"HalKut"
   },
   {
      "id":"16",
      "name":"HottyNaughty",
      "image":"https://i.ibb.co/RQZVnsH/hottnaughty.jpg",
      "genre":"HottyNaughty"
   },
   {
      "id":"17",
      "name":"WOW",
      "image":"https://i.ibb.co/zZrqX73/wow.jpg",
      "genre":"WOW"
   }
   
]
